/**
 * Generates src/App.tsx for plugin-export GrapeJS projects.
 *
 * Public routes render the site normally; /edit (home) and /{path}/edit open GrapeJS.
 */

export interface AppShellTemplateInput {
  siteName: string;
  imports: string;
  pageElementEntries: string;
  defaultPageKey: string;
}

/** Dynamic classNames — plain strings, not nested template literals. */
const CN_PAGES_FAB = 'className={"pages-fab" + (pagesOpen ? " is-open" : "")}';
const CN_PAGES_OVERLAY = 'className={"pages-overlay" + (pagesOpen ? " is-open" : "")}';
const CN_PAGES_SIDEBAR = 'className={"pages-sidebar" + (pagesOpen ? " is-open" : "")}';
const CN_APP_SHELL =
  'className={"app-shell" + (matched?.mode === "edit" ? " is-edit" : " is-view")}';

export function buildAppTsx(input: AppShellTemplateInput): string {
  const { imports, pageElementEntries, defaultPageKey } = input;

  const lines = [
    'import { useEffect, useMemo, useState, type ReactNode } from "react";',
    'import { BrowserRouter, Link, Navigate, NavLink, Route, Routes, useLocation, useParams } from "react-router-dom";',
    'import { SiteLayout } from "./components/layout/SiteLayout";',
    'import { PageView } from "./components/PageView";',
    imports,
    'import siteData from "./data/site.json";',
    "",
    "const pageElements: Record<string, ReactNode> = {",
    pageElementEntries,
    "};",
    "",
    "type PageRoute = {",
    "  key: string;",
    "  title: string;",
    "  path: string;",
    "  editPath: string;",
    "};",
    "",
    "function toPath(route: string | undefined): string {",
    '  if (!route || route === "/") return "/";',
    '  const withSlash = route.startsWith("/") ? route : "/" + route;',
    '  return withSlash.replace(/\\/$/, "") || "/";',
    "}",
    "",
    "function toEditPath(viewPath: string): string {",
    '  return viewPath === "/" ? "/edit" : viewPath + "/edit";',
    "}",
    "",
    "const pageRoutes: PageRoute[] = siteData.pages.map((p) => {",
    "  const path = toPath(p.route);",
    "  return { key: p.key, title: p.title, path, editPath: toEditPath(path) };",
    "});",
    "",
    `const defaultPath = pageRoutes.find((r) => r.key === ${JSON.stringify(defaultPageKey)})?.path ?? "/";`,
    "",
    "function matchPage(pathname: string): { route: PageRoute; mode: \"view\" | \"edit\" } | null {",
    "  const edit = pageRoutes.find((r) => r.editPath === pathname);",
    '  if (edit) return { route: edit, mode: "edit" };',
    "  const view = pageRoutes.find((r) => r.path === pathname);",
    '  if (view) return { route: view, mode: "view" };',
    "  return null;",
    "}",
    "",
    "function EditPage() {",
    "  const { pageKey } = useParams();",
    "  const route = pageRoutes.find((r) => r.key === pageKey) ?? pageRoutes[0];",
    "  if (!route) return <Navigate to={defaultPath} replace />;",
    "  return <SiteLayout mode=\"edit\">{pageElements[route.key]}</SiteLayout>;",
    "}",
    "",
    "function PagesChrome({ children }: { children: ReactNode }) {",
    "  const [pagesOpen, setPagesOpen] = useState(false);",
    "  const [pageQuery, setPageQuery] = useState(\"\");",
    "  const location = useLocation();",
    "  const matched = useMemo(() => matchPage(location.pathname), [location.pathname]);",
    '  const isEdit = matched?.mode === "edit";',
    "  const activeKey = matched?.route.key ?? pageRoutes[0]?.key;",
    "",
    "  const filtered = pageQuery.trim()",
    "    ? pageRoutes.filter(",
    "        (r) =>",
    "          r.title.toLowerCase().includes(pageQuery.toLowerCase()) ||",
    "          r.key.toLowerCase().includes(pageQuery.toLowerCase()) ||",
    "          r.path.toLowerCase().includes(pageQuery.toLowerCase()),",
    "      )",
    "    : pageRoutes;",
    "",
    "  useEffect(() => {",
    "    if (!pagesOpen) return;",
    "    const onKey = (e: KeyboardEvent) => {",
    '      if (e.key === "Escape") setPagesOpen(false);',
    "    };",
    '    window.addEventListener("keydown", onKey);',
    '    return () => window.removeEventListener("keydown", onKey);',
    "  }, [pagesOpen]);",
    "",
    "  return (",
    "    <>",
    "      {children}",
    "",
    "      {!isEdit && matched ? (",
    '        <Link className="edit-page-fab" to={matched.route.editPath} title="Edit this page">',
    "          Edit",
    "        </Link>",
    "      ) : null}",
    "",
    "      {isEdit && matched ? (",
    '        <Link className="view-page-fab" to={matched.route.path} title="View live page">',
    "          View",
    "        </Link>",
    "      ) : null}",
    "",
    "      <button",
    '        type="button"',
    `        ${CN_PAGES_FAB}`,
    "        aria-expanded={pagesOpen}",
    '        aria-controls="pages-sidebar"',
    "        onClick={() => setPagesOpen((v) => !v)}",
    '        title="Pages"',
    "      >",
    '        <span className="pages-fab-label">Pages</span>',
    '        <span className="pages-fab-count">{pageRoutes.length}</span>',
    "      </button>",
    "",
    "      <div",
    `        ${CN_PAGES_OVERLAY}`,
    "        onClick={() => setPagesOpen(false)}",
    "        aria-hidden={!pagesOpen}",
    "      />",
    "",
    "      <aside",
    '        id="pages-sidebar"',
    `        ${CN_PAGES_SIDEBAR}`,
    "        aria-hidden={!pagesOpen}",
    "      >",
    '        <div className="pages-sidebar-head">',
    "          <h2>Pages</h2>",
    '          <button type="button" className="pages-close" onClick={() => setPagesOpen(false)} aria-label="Close">',
    "            ×",
    "          </button>",
    "        </div>",
    '        <div className="pages-search">',
    "          <input",
    '            type="search"',
    "            value={pageQuery}",
    "            onChange={(e) => setPageQuery(e.target.value)}",
    '            placeholder="Search pages…"',
    "          />",
    "        </div>",
    '        <nav className="pages-nav">',
    "          {filtered.map((r) => (",
    '            <div key={r.key} className="pages-nav-row">',
    "              <NavLink",
    "                to={isEdit ? r.editPath : r.path}",
    "                end={r.path === \"/\" && !isEdit}",
    '                className={({ isActive }) => (isActive || activeKey === r.key ? "active" : undefined)}',
    "                onClick={() => {",
    "                  setPagesOpen(false);",
    '                  setPageQuery("");',
    "                }}",
    "              >",
    '                <span className="pages-nav-title">{r.title}</span>',
    '                <span className="pages-nav-path">{isEdit ? r.editPath : r.path}</span>',
    "              </NavLink>",
    "              <NavLink",
    '                className="pages-nav-edit"',
    "                to={isEdit ? r.path : r.editPath}",
    "                onClick={() => setPagesOpen(false)}",
    "              >",
    '                {isEdit ? "View" : "Edit"}',
    "              </NavLink>",
    "            </div>",
    "          ))}",
    '          {filtered.length === 0 && <p className="pages-empty">No pages match</p>}',
    "        </nav>",
    "      </aside>",
    "    </>",
    "  );",
    "}",
    "",
    "function AppRoutes() {",
    "  const location = useLocation();",
    "  const matched = matchPage(location.pathname);",
    "",
    "  return (",
    `    <div ${CN_APP_SHELL}>`,
    '      <div className="app-main">',
    "        <PagesChrome>",
    "          <Routes>",
    "            {pageRoutes.map((r) => (",
    "              <Route",
    "                key={`view-${r.key}`}",
    "                path={r.path}",
    '                element={',
    '                  <SiteLayout mode="view" pageKey={r.key}>',
    "                    <PageView pageKey={r.key} />",
    "                  </SiteLayout>",
    "                }",
    "              />",
    "            ))}",
    "            {pageRoutes.map((r) => (",
    "              <Route",
    "                key={`edit-${r.key}`}",
    "                path={r.editPath}",
    '                element={<SiteLayout mode="edit">{pageElements[r.key]}</SiteLayout>}',
    "              />",
    "            ))}",
    '            <Route path="/page/edit/:pageKey" element={<EditPage />} />',
    '            <Route path="*" element={<Navigate to={defaultPath} replace />} />',
    "          </Routes>",
    "        </PagesChrome>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "export default function App() {",
    "  return (",
    "    <BrowserRouter>",
    "      <AppRoutes />",
    "    </BrowserRouter>",
    "  );",
    "}",
    "",
  ];

  return lines.join("\n");
}

/** Fail fast if generated App.tsx contains the old broken escape pattern. */
export function assertValidAppTsx(source: string): void {
  if (/className=\{\\`/.test(source) || /\\`pages-fab/.test(source)) {
    throw new Error(
      "App.tsx generator produced invalid escaped backticks (className={\\`…\\`}). Regenerate after updating generator/lib/app-shell-template.ts",
    );
  }
  if (!source.includes(CN_PAGES_FAB)) {
    throw new Error("App.tsx generator missing pages-fab className concat");
  }
  if (!source.includes("BrowserRouter") || !source.includes("Routes")) {
    throw new Error("App.tsx generator missing react-router Routes");
  }
  if (!source.includes("PageView") || !source.includes("/edit")) {
    throw new Error("App.tsx generator missing view/edit route split");
  }
}
