import fs from "node:fs";
import path from "node:path";
import type { GrapeBlock } from "./elementor-to-grape/types";
import { pageKeyToComponent } from "./names";

export interface PageSectionSpec {
  fileSlug: string;
  componentName: string;
  displayName: string;
  tagName: string;
  className: string;
  styleAttr?: string;
  attributes: Record<string, string>;
  innerHtml: string;
  fullHtml: string;
}

function blockInnerHtml(block: GrapeBlock): string {
  if (typeof block.components === "string") return block.components;
  if (Array.isArray(block.components)) return JSON.stringify(block.components);
  return block.content ?? "";
}

function attrsToHtml(attrs: Record<string, string> | undefined): string {
  if (!attrs) return "";
  return Object.entries(attrs)
    .filter(([k]) => k !== "style" && k !== "class" && k !== "className")
    .map(([k, v]) => ` ${k}="${String(v).replace(/"/g, "&quot;")}"`)
    .join("");
}

function sectionFileSlug(block: GrapeBlock, index: number): string {
  const hint = sectionTitleHint(block) || block.name || block.tagName || `section-${index + 1}`;
  const slug = String(hint)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
  return `${String(index + 1).padStart(2, "0")}-${slug || `section-${index + 1}`}`;
}

/** Prefer a human title from the first heading inside the section. */
function sectionTitleHint(block: GrapeBlock): string | null {
  const html = blockInnerHtml(block);
  const m = html.match(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i);
  if (!m) return null;
  const text = m[1]!
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&#\d+;/g, " ")
    .replace(/[^a-zA-Z0-9\s-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (!text || text.length < 2) return null;
  return text.slice(0, 60);
}

function safePascalName(raw: string): string {
  const cleaned = raw
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
  // Component identifiers cannot start with a digit.
  const base = cleaned.replace(/^\d+/, "") || "Section";
  return base.slice(0, 48);
}

export function buildSectionSpecs(grapeBlocks: GrapeBlock[]): PageSectionSpec[] {
  const usedNames = new Set<string>();
  return grapeBlocks.map((block, index) => {
    const fileSlug = sectionFileSlug(block, index);
    const titleHint = sectionTitleHint(block);
    let componentName = `Section${String(index + 1).padStart(2, "0")}${safePascalName(
      titleHint || block.name || `Section${index + 1}`,
    )}`;
    // Ensure unique component names within a page.
    let unique = componentName;
    let n = 2;
    while (usedNames.has(unique)) {
      unique = `${componentName}${n++}`;
    }
    usedNames.add(unique);

    const tagName = (block.tagName || "section").toLowerCase();
    const className = (block.classes ?? []).join(" ");
    const attributes: Record<string, string> = {};
    if (block.attributes) {
      for (const [k, v] of Object.entries(block.attributes)) {
        if (v == null) continue;
        attributes[k] = String(v);
      }
    }
    const styleAttr = attributes.style;
    const innerHtml = blockInnerHtml(block);
    const classAttr = className ? ` class="${className.replace(/"/g, "&quot;")}"` : "";
    const styleHtml = styleAttr ? ` style="${styleAttr.replace(/"/g, "&quot;")}"` : "";
    const fullHtml = `<${tagName}${classAttr}${styleHtml}${attrsToHtml(attributes)}>${innerHtml}</${tagName}>`;

    return {
      fileSlug,
      componentName: unique,
      displayName: titleHint || block.name || `Section ${index + 1}`,
      tagName,
      className,
      styleAttr,
      attributes,
      innerHtml,
      fullHtml,
    };
  });
}

function writeSectionComponent(filePath: string, spec: PageSectionSpec, pageKey: string): void {
  const markupLiteral = JSON.stringify(spec.fullHtml);
  const content = `/**
 * Page section: ${spec.displayName}
 * Source page: ${pageKey} · ${spec.fileSlug}
 * Auto-generated by Migration Studio — edit freely; re-convert will overwrite.
 */
export function ${spec.componentName}() {
  return (
    <div
      className="page-section"
      data-page-key=${JSON.stringify(pageKey)}
      data-section=${JSON.stringify(spec.fileSlug)}
      data-section-name=${JSON.stringify(spec.displayName)}
      dangerouslySetInnerHTML={{ __html: ${markupLiteral} }}
    />
  );
}
`;
  fs.writeFileSync(filePath, content, "utf8");
}

function writePageBody(filePath: string, pageKey: string, specs: PageSectionSpec[]): void {
  const pageComponent = `${pageKeyToComponent(pageKey)}Body`;
  const imports = specs
    .map((s) => `import { ${s.componentName} } from "./${s.componentName}";`)
    .join("\n");
  const children = specs.map((s) => `      <${s.componentName} />`).join("\n");

  const content = `/**
 * Composed body for page "${pageKey}".
 * Each child is an independent section component under this folder.
 */
${imports}

export function ${pageComponent}() {
  return (
    <div className="page-body" data-page-key=${JSON.stringify(pageKey)} data-sections={${specs.length}}>
${children}
    </div>
  );
}

export const ${pageComponent}Sections = [
${specs.map((s) => `  ${s.componentName},`).join("\n")}
] as const;
`;
  fs.writeFileSync(filePath, content, "utf8");
}

/**
 * Emit React section components for every page that has grapeBlocks.
 *
 * Layout:
 *   src/components/pages/{pageKey}/Section01….tsx
 *   src/components/pages/{pageKey}/index.tsx
 *   src/components/pages/registry.ts
 */
export function writePageSectionReactComponents(
  projectDir: string,
  pages: Array<{ key: string; grapeBlocks?: GrapeBlock[] | null }>,
): { pagesWithSections: number; sectionCount: number } {
  const pagesRoot = path.join(projectDir, "src", "components", "pages");
  fs.mkdirSync(pagesRoot, { recursive: true });

  // Clear previous generated page folders (keep registry rewrite below).
  for (const entry of fs.readdirSync(pagesRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    fs.rmSync(path.join(pagesRoot, entry.name), { recursive: true, force: true });
  }

  const registryEntries: string[] = [];
  const registryImports: string[] = [];
  let sectionCount = 0;
  let pagesWithSections = 0;

  for (const page of pages) {
    const blocks = page.grapeBlocks;
    if (!Array.isArray(blocks) || blocks.length === 0) continue;

    const specs = buildSectionSpecs(blocks);
    if (!specs.length) continue;

    pagesWithSections++;
    sectionCount += specs.length;

    const pageDir = path.join(pagesRoot, page.key);
    fs.mkdirSync(pageDir, { recursive: true });

    for (const spec of specs) {
      writeSectionComponent(path.join(pageDir, `${spec.componentName}.tsx`), spec, page.key);
    }
    writePageBody(path.join(pageDir, "index.tsx"), page.key, specs);

    const bodyName = `${pageKeyToComponent(page.key)}Body`;
    registryImports.push(`import { ${bodyName} } from "./${page.key}";`);
    registryEntries.push(`  ${JSON.stringify(page.key)}: ${bodyName},`);
  }

  const registry = `import type { ComponentType } from "react";
${registryImports.join("\n")}

/** Maps site.json page keys → composed React page-body components. */
export const PAGE_BODIES: Record<string, ComponentType> = {
${registryEntries.join("\n")}
};

export function hasPageBody(pageKey: string): boolean {
  return Boolean(PAGE_BODIES[pageKey]);
}
`;
  fs.writeFileSync(path.join(pagesRoot, "registry.ts"), registry, "utf8");

  return { pagesWithSections, sectionCount };
}
